# Generated by Django 4.2.2 on 2023-06-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('bname', models.CharField(default='', max_length=100)),
                ('number_of_chapters', models.IntegerField(default=0)),
                ('number_of_exercises', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'BOOK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chid', models.AutoField(primary_key=True, serialize=False)),
                ('chname', models.CharField(default='', max_length=100)),
                ('number_of_sections', models.IntegerField(default=0)),
                ('number_of_exercises', models.IntegerField(default=0)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
            options={
                'db_table': 'CHAPTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instid', models.AutoField(primary_key=True, serialize=False)),
                ('ifirst_name', models.CharField(max_length=50)),
                ('ilast_name', models.CharField(max_length=50)),
                ('iphone_number', models.CharField(max_length=20)),
                ('iemail', models.CharField(max_length=255)),
                ('icountry', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'INSTRUCTOR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('secid', models.AutoField(primary_key=True, serialize=False)),
                ('secname', models.CharField(default='', max_length=100)),
                ('number_of_exercises', models.IntegerField(default=0)),
                ('chid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
            ],
            options={
                'db_table': 'SECTION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sfirst_name', models.CharField(default='', max_length=50)),
                ('slast_name', models.CharField(default='', max_length=50)),
                ('sphone_number', models.CharField(default='', max_length=20)),
                ('semail', models.CharField(default='', max_length=255)),
                ('scountry', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'STUDENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=0)),
                ('chid', models.IntegerField(default=0)),
                ('ability', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('discrimination', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('difficulty', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('number_of_attempts', models.IntegerField(default=0)),
                ('number_of_hints', models.IntegerField(default=0)),
                ('number_of_incorrect_attempts', models.IntegerField(default=0)),
                ('timespent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('enroll_year', models.DateField()),
            ],
            options={
                'db_table': 'STUDENT_CHAPTER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(default=0)),
                ('secid', models.IntegerField(default=0)),
                ('ability', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('discrimination', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('difficulty', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('number_of_attempts', models.IntegerField(default=0)),
                ('number_of_hints', models.IntegerField(default=0)),
                ('number_of_incorrect_attempts', models.IntegerField(default=0)),
                ('timespent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('enroll_year', models.DateField()),
            ],
            options={
                'db_table': 'STUDENT_SECTION',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exid', models.IntegerField(default=0)),
                ('sid', models.IntegerField(default=0)),
                ('number_of_attempts', models.IntegerField(default=0)),
                ('number_of_hints', models.IntegerField(default=0)),
                ('number_of_incorrect_attempts', models.IntegerField(default=0)),
                ('solved', models.BooleanField(default=False)),
                ('ability', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('discrimination', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('difficulty', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('timespent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('chid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
                ('secid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
            options={
                'db_table': 'STUDENT_EXERCISE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('discrimination', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('difficulty', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('number_of_attempts', models.IntegerField(default=0)),
                ('number_of_hints', models.IntegerField(default=0)),
                ('number_of_incorrect_attempts', models.IntegerField(default=0)),
                ('timespent', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
                ('enroll_year', models.DateField()),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
            options={
                'db_table': 'STUDENT_BOOK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstructorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('instid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.instructor')),
            ],
            options={
                'db_table': 'INSTRUCTOR_BOOK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exid', models.AutoField(primary_key=True, serialize=False)),
                ('exname', models.CharField(default='', max_length=100)),
                ('number_of_attempts', models.IntegerField(default=0)),
                ('number_of_hints', models.IntegerField(default=0)),
                ('number_of_incorrect_attempts', models.IntegerField(default=0)),
                ('number_of_correct', models.IntegerField(default=0)),
                ('secid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
            options={
                'db_table': 'EXERCISE',
                'managed': True,
            },
        ),
    ]
